//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMagazine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JournalEntities : DbContext
    {
        public JournalEntities()
            : base("name=JournalEntities")
        {
        }
        public static JournalEntities _context;
        public static JournalEntities GetContext()
        {
            if (_context == null)
            {
                _context = new JournalEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Classes> Classes { get; set; }
        public DbSet<Discipline> Discipline { get; set; }
        public DbSet<DisTeacher> DisTeacher { get; set; }
        public DbSet<Grades> Grades { get; set; }
        public DbSet<GroupTeacher> GroupTeacher { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Students> Students { get; set; }
        public DbSet<Teachers> Teachers { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
